import streamlit as st
import PyPDF2
from langchain_community.chat_models import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from fpdf import FPDF
import datetime

# --- PAGE CONFIG ---
st.set_page_config(page_title="ScopeLock", page_icon="🔒", layout="wide")

# Load Custom CSS
def local_css(file_name):
    try:
        with open(file_name) as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
    except FileNotFoundError:
        st.warning("styles.css not found. Please ensure it exists.")

local_css("styles.css")

# --- HELPER FUNCTIONS ---

def extract_text_from_pdf(uploaded_file):
    pdf_reader = PyPDF2.PdfReader(uploaded_file)
    text = ""
    for page in pdf_reader.pages:
        text += page.extract_text()
    return text

def analyze_scope(contract_text, request_text):
    # Initialize Ollama (Llama 3)
    llm = ChatOllama(model="llama3", temperature=0)
    
    prompt = ChatPromptTemplate.from_template("""
        You are a strict Project Manager for a technical agency using the tool "ScopeLock".
        You have two inputs:
        1. A signed CONTRACT (SOW).
        2. A CLIENT REQUEST (Email).

        Your Goal: Determine if the CLIENT REQUEST is strictly "IN SCOPE" or "OUT OF SCOPE" based on the CONTRACT.

        Rules:
        - Be conservative. If it's not explicitly listed in the contract, it is OUT OF SCOPE.
        - If OUT OF SCOPE, draft a polite but firm response email.
        - If OUT OF SCOPE, estimate a price (guess based on complexity, e.g. $200-$2000).
        
        Format your response exactly like this:
        VERDICT: [IN SCOPE or OUT OF SCOPE]
        REASONING: [1-2 sentences citing the contract section or lack thereof]
        EMAIL_DRAFT: [The draft email]
        ESTIMATED_PRICE: [Price if out of scope, else N/A]
        
        CONTRACT: {contract}
        CLIENT REQUEST: {request}
    """)
    
    chain = prompt | llm
    try:
        response = chain.invoke({"contract": contract_text, "request": request_text})
        return response.content
    except Exception as e:
        return f"Error connecting to Ollama: {str(e)}. Make sure Ollama is running."

def create_change_order_pdf(client_name, description, price):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Header
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(190, 15, txt="CHANGE ORDER", ln=1, align='C')
    pdf.line(10, 30, 200, 30)
    pdf.ln(10)
    
    # Details
    pdf.set_font("Arial", size=12)
    pdf.cell(190, 10, txt=f"Generated by ScopeLock", ln=1, align='R')
    pdf.cell(190, 10, txt=f"Client: {client_name}", ln=1, align='L')
    pdf.cell(190, 10, txt=f"Date: {datetime.date.today()}", ln=1, align='L')
    pdf.ln(10)
    
    # Scope
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(190, 10, txt="Description of Additional Work:", ln=1, align='L', fill=True)
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(190, 10, txt=description)
    pdf.ln(5)
    
    # Price
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 15, txt=f"Total Additional Cost: {price}", ln=1, align='R')
    
    return pdf.output(dest='S').encode('latin-1')

# --- SIDEBAR ---
with st.sidebar:
    st.title("🔒 ScopeLock")
    st.caption("The Scope Creep Watchdog")
    st.markdown("---")
    uploaded_file = st.file_uploader("1. Upload Signed SOW (PDF)", type="pdf")
    
    st.markdown("### Project Settings")
    client_name = st.text_input("Client Name", value="Acme Corp")
    
    st.success("System Status: Online")

# --- MAIN APP ---
st.title("Analyze New Request")
st.markdown("Paste the client's email below. ScopeLock will cross-reference it with your PDF contract.")

client_request = st.text_area("2. Client Request / Email", height=200, placeholder="Example: 'Hi, can we also add a dark mode and a mobile app? We need this by Friday...'")

if st.button("Analyze Scope", type="primary"):
    if not uploaded_file:
        st.error("⚠️ Please upload a PDF Contract (SOW) in the sidebar first.")
    elif not client_request:
        st.error("⚠️ Please paste the client request.")
    else:
        with st.spinner("🔒 ScopeLock is analyzing your contract logic..."):
            # 1. Read PDF
            contract_text = extract_text_from_pdf(uploaded_file)
            
            # 2. Ask AI
            result = analyze_scope(contract_text, client_request)
            
            # 3. Display Result
            st.markdown("### Analysis Result")
            
            # Simple parsing (robustness can be improved in v2)
            verdict = "OUT OF SCOPE" if "OUT OF SCOPE" in result else "IN SCOPE"
            badge_class = "badge-out" if verdict == "OUT OF SCOPE" else "badge-in"
            
            st.markdown(f"""
            <div class="scope-card">
                <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:15px;">
                    <span class="{badge_class}">{verdict}</span>
                    <small style="color:#64748b">Verified by Llama 3</small>
                </div>
                <div style="white-space: pre-wrap; font-family: sans-serif; line-height: 1.6;">{result}</div>
            </div>
            """, unsafe_allow_html=True)
            
            # 4. Upsell: Generate PDF
            if verdict == "OUT OF SCOPE":
                st.info("💡 Opportunity detected: Generate a Change Order to get paid for this work.")
                
                pdf_data = create_change_order_pdf(client_name, client_request[:200] + "...", "$500 (Est)")
                
                st.download_button(
                    label="📄 Download Official Change Order (PDF)",
                    data=pdf_data,
                    file_name="ScopeLock_Change_Order.pdf",
                    mime="application/pdf"
                )
